[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && pip install -e ."

[deploy]
startCommand = "gunicorn wsgi:application --log-level debug --workers 1 --timeout 120 --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure" 