[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn wsgi:application"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure" 